language: php
php:
  - 5.5
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 5.5

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
